// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChQ_WEsn6pTRzvT_zgovKmGDk95WYPx_I',
    appId: '1:211503743534:web:b4d99f01eb7469517095bf',
    messagingSenderId: '211503743534',
    projectId: 'kujitoon',
    authDomain: 'kujitoon.firebaseapp.com',
    storageBucket: 'kujitoon.firebasestorage.app',
    measurementId: 'G-ZF5MMVB3Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL99C-EG2CunuWbEiKYASfmLjiW-vg_7M',
    appId: '1:211503743534:android:0d9a1d3ce81460767095bf',
    messagingSenderId: '211503743534',
    projectId: 'kujitoon',
    storageBucket: 'kujitoon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANPeMAdOSiGFM6KBqu3VfM6n3nJFORAnU',
    appId: '1:211503743534:ios:8f48d53d9ccb80757095bf',
    messagingSenderId: '211503743534',
    projectId: 'kujitoon',
    storageBucket: 'kujitoon.firebasestorage.app',
    iosBundleId: 'duykr.studio.kujitoon',
  );
}
